FROM python:3.10

# Install GDAL dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gdal-bin \
        libgdal-dev && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables for GDAL
ENV GDAL_DATA /usr/share/gdal

# Set the working directory
WORKDIR /app

# Add a non-root user and switch to it
RUN adduser --disabled-password --gecos "" myuser
# Set PATH to include the .local/bin directory for the non-root user
ENV PATH="/home/myuser/.local/bin:${PATH}"

USER myuser

# Copy only necessary notebook files
COPY notebooks/*.ipynb .

# Copy the requirements file and set ownership
COPY --chown=myuser:myuser requirements_jupyterlab.txt .

# Upgrade pip and install requirements
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_jupyterlab.txt

# Switch back to root to remove the file, then revert to myuser
USER root
RUN rm requirements_jupyterlab.txt
USER myuser

# Expose the port for Jupyter Notebook
EXPOSE 8888

# Command to run Jupyter Lab
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--ServerApp.token=''"]
